name: app
description: A forum application to support community discussion for meal planning, sustainable practices, and education

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test: ^1.0.0
  mockito: ^4.1.4

flutter:
  uses-material-design: true
